[SERVICE]
    Flush        5
    Log_Level    info

[INPUT]
    Name              tail
    Path              /var/log/*.log
    Parser            syslog
    Tag               logs.*

[OUTPUT]
    Name              forward
    Match             *
    Host              127.0.0.1
    Port              24224
